name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: create new release
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: "emojis=true"
