name: Test coverage
on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }}
