name: Test coverage
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.15
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }}
